#!/usr/bin/env perl
# Generated by generateAuthorTests. Do not edit, regenerate instead.
use strict;
use warnings;

use Test::More;

BEGIN {
    eval { require AuthorTests; 1 }
        or plan skip_all => 'AuthorTests not installed (author-only checks)';
}

AuthorTests::run('compile');
